sudo: required
services:
  - docker
  
before_install:
  - docker build -t brianr/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run -e CI=true brianr/react-test -- --coverage
  
after_success:
  - docker build -t brianr/multi-client ./client
  - docker build -t brianr/multi-nginx ./nginx
  - docker build -t brianr/multi-server ./server
  - docker build -t brianr/multi-worker ./worker
  # Log in to the docker CLI
  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push brianr/multi-client
  - docker push brianr/multi-nginx
  - docker push brianr/multi-server
  - docker push brianr/multi-worker
